CREATE TABLE toll_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tgl_report DATE,
    no_kartu VARCHAR(50),
    kode_cabang VARCHAR(10),
    nama_cabang VARCHAR(100),
    gerbang VARCHAR(10),
    nama_gerbang VARCHAR(100),
    kode_gardu VARCHAR(10),
    tgl_transaksi DATETIME,
    bank VARCHAR(50),
    shift VARCHAR(10),
    periode VARCHAR(20),
    tarif INT,
    saldo INT,
    no_resi VARCHAR(50),
    id_pultol VARCHAR(50),
    id_kspt VARCHAR(50),
    kode_gerbang_asal VARCHAR(10),
    golongan VARCHAR(20),
    created_at DATETIME,
    updated_at DATETIME,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    nama_gerbang_asal VARCHAR(100),
    flag_id VARCHAR(10)
);
